version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.7.1-20221208
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=3

  chrome_video:
      image: selenium/video:ffmpeg-4.3.1-20221208
      volumes:
        - ./tmp/videos:/videos
      depends_on:
        - chrome
      environment:
        - DISPLAY_CONTAINER_NAME=chrome
        - FILE_NAME=execution.mp4


  edge:
    image: selenium/node-edge:4.7.1-20221208
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1

  edge_video:
    image: selenium/video:ffmpeg-4.3.1-20221208
    volumes:
      - ./tmp/videos:/videos
    depends_on:
      - edge
    environment:
      - DISPLAY_CONTAINER_NAME=edge
      - FILE_NAME=execution.mp4

  firefox:
    image: selenium/node-firefox:4.7.1-20221208
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=3

  firefox_video:
    image: selenium/video:ffmpeg-4.3.1-20221208
    volumes:
      - ./tmp/videos:/videos
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - FILE_NAME=execution.mp4

  selenium-hub:
    image: selenium/hub:4.7.1-20221208
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"




#cd docker
#docker-compose -f docker-compose-hubNode.yml up -d
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
